name: freebsd

on:
  schedule:
    - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ secrets.VERSION }}
      CPU: ${{ matrix.target }}
      OS: ${{ matrix.os }}
      VARIANT: ${{ matrix.suffix == 'yes' && format('-{0}', matrix.release) || ''}}
      LINKFLAGS: ${{ matrix.linkflags }}
      CLISP_LDFLAGS: ${{ matrix.clispldflags }}
      CC: ${{ matrix.target == 'x86' && 'cc -m32' || 'cc' }}
      ROSWELL_BRANCH: master
      GH_USER: roswell
      GH_REPO: clisp_head
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        release: ['13.2', '13.3', '14.0', '14.1']
        target: [x86-64, x86, arm64]
        suffix: [yes]
        os: [freebsd]
        lisp: [sbcl-bin/2.4.8]
        include:
          - release: 13.3
            target: x86-64
            suffix: no
            lisp: sbcl-bin/2.2.9
            os: freebsd
          - release: 13.3
            target: x86
            suffix: no
            lisp: sbcl-bin/2.2.9
            os: freebsd
          - release: 13.3
            target: arm64
            suffix: no
            lisp: sbcl-bin/2.3.0
            os: freebsd
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v4
      - name: setenv
        run: |
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "ROSWELL_BRANCH=release" >> $GITHUB_ENV
      - name: checkenv
        run: |
          uname -s
          uname -m
          echo $ROSWELL_INSTALL_DIR
          echo $ROSWELL_BRANCH
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
          ros install snmsts/sn.github roswell/sbcl_bin
      - name: check uploaded
        id: check_uploaded
        env:
          VERSION: ${{ secrets.VERSION }}
          CPU: ${{ matrix.target }}
          OS: ${{ matrix.os }}
          VARIANT: ${{ matrix.suffix == 'yes' && format('-{0}', matrix.release) || ''}}
        run: make latest-version upload-archive-p
        continue-on-error: true
      - if: ${{ matrix.target != 'x86' && steps.check_uploaded.outcome == 'failure'}}
        name: Test on FreeBSD
        uses: cross-platform-actions/action@v0.25.0
        with:
          environment_variables: VERSION CPU OS VARIANT LINKFLAGS CLISP_LDFLAGS CC GH_USER GH_REPO GITHUB_OAUTH_TOKEN
          operating_system: ${{ matrix.os }}
          architecture: ${{ matrix.target == 'x86' && 'x86-64' || matrix.target }}
          version: ${{ matrix.release }}
          shell: bash
          run: |
            uname -a
            freebsd-version
            whoami
            pwd
            sudo env IGNORE_OSVERSION=yes pkg update -f
            sudo pkg install -y bash roswell autoconf texinfo perl5 gmake gcc libffi git
            ros install ${{ matrix.lisp }}
            ros install snmsts/sn.github roswell/sbcl_bin
            gmake latest-version compile archive;
            env FILE=`ls *.bz2` gmake latest-version upload-archive;
      - if: ${{ matrix.target == 'x86' && steps.check_uploaded.outcome == 'failure' }}
        name: Test on FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          envs: 'VERSION CPU OS VARIANT LINKFLAGS CLISP_LDFLAGS CC GH_USER GH_REPO GITHUB_OAUTH_TOKEN'
          usesh: true
          prepare: |
            pkg install -y bash roswell autoconf texinfo perl5 gmake gcc libffi git
            ros install ${{ matrix.lisp }}
            ros install snmsts/sn.github roswell/sbcl_bin
          run: |
            gmake latest-version compile archive;
            env FILE=`ls *.bz2` gmake latest-version upload-archive;
