name: osx

on:
  schedule:
    - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        lisp: [sbcl-bin/2.0.0]
        target: [x86-64]
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v2

      - name: setenv
        run: |
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "ROSWELL_BRANCH=release" >> $GITHUB_ENV
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew install automake autoconf
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install snmsts/sn.github roswell/sbcl_bin
          curl -L -O https://raw.githubusercontent.com/roswell/clisp_bin/main/Makefile
      - name: build & upload
        env:
          VERSION: ${{ secrets.VERSION }}
          CPU: ${{ matrix.target }}
          OS: darwin
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ matrix.target }}
        run: |
          make latest-version checkout-clisp
          rm -f clisp/version.sh
          make latest-version clisp/version.sh compile archive
      - name: upload
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ secrets.VERSION }}
          CPU: ${{ matrix.target }}
          VARIANT: ${{ matrix.suffix }}
        run: |
          env FILE=`ls *.bz2` make latest-version upload-archive;
