name: osx

on:
  schedule:
    - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target == 'arm64' && 'macos-14' || 'macOS-12' }}
    strategy:
      fail-fast: false
      matrix:
        lisp: [sbcl-bin/2.3.8]
        target: [arm64, x86-64]
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v4

      - name: setenv
        run: |
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "ROSWELL_BRANCH=release" >> $GITHUB_ENV
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew install automake autoconf
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install snmsts/sn.github roswell/sbcl_bin
      - name: build & upload
        env:
          VERSION: ${{ secrets.VERSION }}
          CPU: ${{ matrix.target }}
          OS: darwin
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ matrix.target }}
          CFLAGS: -mmacosx-version-min=10.9
          CXXFLAGS: -mmacosx-version-min=10.9
          LDFLAGS: -mmacosx-version-min=10.9
        run: |
          make latest-version clisp
          cat clisp/version.sh
          rm -f clisp/version.sh
          make latest-version clisp/version.sh
          cat clisp/version.sh
          make latest-version compile archive
      - name: upload
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ secrets.VERSION }}
          CPU: ${{ matrix.target }}
          VARIANT: ${{ matrix.suffix }}
        run: |
          env FILE=`ls *.bz2` make latest-version upload-archive;
